export const AUTH_ACTIONS = {
  HANDLE_REGISTER_CHANGE: "HANDLE_REGISTER_CHANGE",
  HANDLE_LOGIN_CHANGE: "HANDLE_LOGIN_CHANGE",
  HANDLE_PROFILE_CHANGE: "HANDLE_PROFILE_CHANGE",
  GET_USER_PROFILE: "GET_USER_PROFILE",
} as const;
