export const PRODUCT_ACTIONS = {
  HANDLE_PRODUCT_CHANGE: "HANDLE_PRODUCT_CHANGE",
  HANDLE_PRODUCT_FILE_CHANGE: "HANDLE_PRODUCT_FILE_CHANGE",
  GET_PRODUCT_LIST: "GET_PRODUCT_LIST",
  GET_PRODUCT_DETAIL: "GET_PRODUCT_DETAIL",
  GET_PRODUCT_CATEGORY: "GET_PRODUCT_CATEGORY",
} as const;
