export const CATEGORY_ACTIONS = {
  HANDLE_CATEGORY_CHANGE: "HANDLE_CATEGORY_CHANGE",
  HANDLE_CATEGORY_FILE_CHANGE: "HANDLE_CATEGORY_FILE_CHANGE",
  GET_CATEGORY_LIST: "GET_CATEGORY_LIST",
} as const;
